import scipy

print(scipy.constants.nano)
print(scipy.constants.alpha)
print(scipy.constants.acre)
print(scipy.constants.bar)
print(scipy.constants.atmosphere)
print(scipy.constants.kilo)
print(scipy.constants.mil)
print(scipy.constants.giga)
print(scipy.constants.mega)
print(scipy.constants.kmh)
print(scipy.constants.calorie)
print(scipy.constants.btu)
print(scipy.constants.mph)
print(scipy.constants.atm)
print(scipy.constants.hour)
print(scipy.constants.degree)
print(scipy.constants.bar)
print(scipy.constants.k)
print(scipy.constants.point)
print(scipy.constants.yard)
print(scipy.constants.zero_Celsius)
print(scipy.constants.pi)
print(scipy.constants.hp)
print(scipy.constants.kgf)
print(scipy.constants.codata)
print(scipy.constants.liter)
print(scipy.constants.litre)

print(scipy.constants.Btu)
